# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200429_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.CharField(default='', max_length=20),
        ),
    ]
