# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200429_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
