# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=1),
        ),
    ]
