# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200429_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='further_information',
            field=models.TextField(),
        ),
    ]
