# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
